language: go

go:
  - 1.10.x
  - 1.11.x
  - 1.12.x
  - 1.13.x
  # - 1.14.x

env:
  global:
    - GO111MODULE=on
    - CC_TEST_REPORTER_ID=a68ad3c72a402d4a6b564f8a431ca2f3f5c72b179d73f9eadcf554461119d106

go_import_path: github.com/JigneshSatam/parallel

before_install:
  - go get -v golang.org/x/lint/golint

git:
  depth: 1

os: [linux, osx]
# os: [linux, osx, windows]

# script:
#   - go test -race -v -coverprofile c.out ./...
#   # - go test -race -v ./...


before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - go test -race -v -coverprofile c.out ./...


after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
